declare const styles: {
  readonly container: string;
  readonly title: string;
  readonly text: string;
  readonly wrapper: string;
  readonly window: string;
  readonly windowTitle: string;
  readonly windowContents: string;
  readonly controlBtn: string;
  readonly guide: string;
  readonly extensionWrapper: string;
  readonly linkToGuide: string;
  readonly chromeExtension: string;
  readonly firefoxExtension: string;
  readonly linkTextSmall: string;
  readonly linkTextBig: string;
  readonly list: string;
  readonly numberedList: string;
  readonly onchainGuide: string;
};
export = styles;
