declare const styles: {
  readonly container: string;
  readonly title: string;
  readonly text: string;
  readonly topText: string;
  readonly bottomText: string;
  readonly wrapper: string;
  readonly claimContainer: string;
  readonly controlBtn: string;
  readonly claimContents: string;
  readonly steps: string;
  readonly step: string;
  readonly selectAccount: string;
  readonly stepsHeading: string;
  readonly btn: string;
  readonly select: string;
  readonly selectShow: string;
  readonly options: string;
  readonly selectText: string;
  readonly option: string;
  readonly optionText: string;
};
export = styles;
