declare const styles: {
  readonly container: string;
  readonly search: string;
  readonly searchBar: string;
  readonly infoTextAddress: string;
  readonly button: string;
  readonly infoText: string;
  readonly input: string;
  readonly results: string;
  readonly didDocument: string;
  readonly endpoints: string;
  readonly title: string;
  readonly main: string;
  readonly mainResults: string;
  readonly text: string;
  readonly top: string;
  readonly modal: string;
  readonly infoContainer: string;
  readonly infoBtn: string;
  readonly modeContainer: string;
  readonly takenMode: string;
  readonly availableMode: string;
};
export = styles;
