declare const styles: {
  readonly container: string;
  readonly search: string;
  readonly searchBar: string;
  readonly button: string;
  readonly input: string;
  readonly infoText: string;
  readonly infoTextAddress: string;
  readonly main: string;
  readonly results: string;
  readonly noWeb3name: string;
  readonly title: string;
  readonly infoContainer: string;
  readonly infoBtn: string;
  readonly modeContainer: string;
  readonly availableActiveMode: string;
  readonly availableInactiveMode: string;
  readonly takenActiveMode: string;
  readonly takenInactiveMode: string;
  readonly modal: string;
  readonly text: string;
  readonly top: string;
};
export = styles;
