declare const styles: {
  readonly container: string;
  readonly type: string;
  readonly endpoint: string;
  readonly urlContainer: string;
  readonly url: string;
  readonly button: string;
  readonly open: string;
  readonly close: string;
  readonly loader: string;
  readonly seperator: string;
  readonly titleWrapper: string;
  readonly title: string;
  readonly infoBtn: string;
  readonly didDocument: string;
  readonly endpoints: string;
  readonly endpointWrapper: string;
  readonly modalText: string;
  readonly top: string;
  readonly modal: string;
};
export = styles;
