name: Release workflow
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Choose environment tag"
        required: true
        type: choice
        options:
          - smoke
          - dev
          - stg
          - test
          - prod
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.tag }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v5

      - name: Configure Node and package manager
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: 'package.json'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build code
        run: yarn build

      - name: Test size
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
        run: yarn run test-size

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'
      - name: Create .env file
        run: |
          echo "REACT_APP_CHAIN_ENDPOINT=${{ vars.REACT_APP_CHAIN_ENDPOINT }}" >> .env
          echo "REACT_APP_CHECKOUT_URL=${{ vars.REACT_APP_CHECKOUT_URL }}" >> .env
          echo "REACT_APP_IS_TEST_ENV=${{ vars.REACT_APP_IS_TEST_ENV }}" >> .env
          echo "REACT_APP_MAINTENANCE=${{ vars.REACT_APP_MAINTENANCE }}" >> .env
          echo "REACT_APP_TXD_URL=${{ vars.REACT_APP_TXD_URL }}" >> .env
          echo "REACT_APP_UNIRESOLVER_ENDPOINT=${{ vars.REACT_APP_UNIRESOLVER_ENDPOINT }}" >> .env
        shell: bash

      - name: Build image
        run: |
          docker build -t w3n:latest .

      - name: Tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: w3n
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag w3n $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.event.inputs.tag }}
          docker tag w3n $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.event.inputs.tag }}
